Repository InternationalScratchWiki/scratch-confirmaccount-v3, pull requests merged in 2020-09, with the labels that each got.

#17 fix
  README.md
Labels: documentation

#15 fix exception
  src/database/DatabaseInteractions.php
Labels: bug

#19 Fix name collision with ScratchLogin
  src/SpecialRequestAccount.php
  src/verification/ScratchVerification.php
Labels: bug

#18 Translated to Turkish!
  i18n/tr.json
Labels: i18n, pr - needs review

#20 Fully i18n
  extension.json
  i18n/en.json
  resources/main.css
  src/SpecialConfirmAccounts.php
  src/SpecialRequestAccount.php
Labels: i18n

#22 Fix done messages
  i18n/en.json
Labels: i18n

#24 Add password hash to DB and use it when creating
  i18n/en.json
  sql/requests.sql
  src/SpecialRequestAccount.php
  src/common.php
  src/database/DatabaseInteractions.php
  src/objects/AccountRequest.php
Labels: enhancement, pr - needs review

#28 i18n new messages
  i18n/en.json
  src/RequestPage.php
  src/SpecialConfirmAccounts.php
  src/SpecialRequestAccount.php
Labels: i18n

#31 Better RecentChanges bar
  i18n/en.json
  resources/main.css
  src/ScratchConfirmAccountHooks.php
  src/SpecialRequestAccount.php
  src/database/DatabaseInteractions.php
Labels: enhancement

#35 Scratch integration
  README.md
  extension.json
  i18n/en.json
  resources/main.css
  src/RequestPage.php
  src/SpecialRequestAccount.php
  src/database/DatabaseInteractions.php
  src/email.php
  src/objects/AccountRequest.php
  src/verification/ScratchUserCheck.php
Labels: enhancement, pr - needs work

#37 More optimizations
  extension.json
  i18n/en.json
  resources/main.js
  src/RequestPage.php
  src/ScratchConfirmAccountHooks.php
  src/SpecialConfirmAccounts.php
  src/database/DatabaseInteractions.php
Labels: enhancement, i18n, pr - needs review

#39 Link request page in many places
  extension.json
  i18n/en.json
  src/ScratchConfirmAccountHooks.php
  src/SpecialRequestAccount.php
Labels: enhancement, pr - needs review

#40 Fix incorrect ORDER BY syntax
  src/database/DatabaseInteractions.php
Labels: bug

#42 Add CSRF protection
  i18n/en.json
  src/RequestPage.php
  src/SpecialConfirmAccounts.php
  src/SpecialRequestAccount.php
  src/common.php
Labels: bugfix

#41 Show specific error when fetching profile failed
  i18n/en.json
  src/SpecialRequestAccount.php
  src/verification/ScratchUserCheck.php
Labels: enhancement

#47 Fix typo
  src/RequestPage.php
Labels: bugfix

#48 Assume nothing if profile parsing failed
  src/verification/ScratchUserCheck.php
Labels: bugfix

#49 Don't change status by user if it is New request
  src/RequestPage.php
  src/database/DatabaseInteractions.php
Labels: bugfix

#50 Fix AccountRequest.lastUpdated not being set
  src/objects/AccountRequest.php
Labels: bugfix

#52 Japanese i18n
  i18n/ja.json
Labels: i18n

#53 Document new messages
  i18n/en.json
  i18n/qqq.json
Labels: i18n

#55 Tranlated to Turkish completely
  i18n/en.json
  i18n/tr.json
Labels: i18n

#61 CheckUser integration
  i18n/en.json
  i18n/qqq.json
  resources/main.css
  sql/requests.sql
  src/RequestPage.php
  src/SpecialRequestAccount.php
  src/database/CheckUserIntegration.php
  src/database/DatabaseInteractions.php
  src/objects/AccountRequest.php
Labels: enhancement, pr - needs review

#64 Fix potential XSS with crafted system message
  src/SpecialRequestAccount.php
Labels: bugfix

#65 Update Japanese i18n
  i18n/ja.json
Labels: i18n
