Repository InternationalScratchWiki/scratch-confirmaccount-v3, pull requests merged in 2020-10, with the labels that each got.

#67 Welcome users on talk page
  README.md
  extension.json
  i18n/en.json
  i18n/ja.json
  i18n/qqq.json
  src/RequestPage.php
  src/database/DatabaseInteractions.php
Labels: enhancement

#68 Use different messages for headers
  i18n/en.json
  i18n/ja.json
  i18n/qqq.json
  src/SpecialConfirmAccounts.php
Labels: i18n

#79 changed actions label for requesters (closes #43)
  i18n/en.json
  src/RequestPage.php
Labels: enhancement

#82 Added atomic database operations to avoid race conditions
  src/PurgeAccountRequestPasswordsJob.php
  src/RequestPage.php
  src/ScratchConfirmAccountHooks.php
  src/SpecialConfirmAccounts.php
  src/SpecialRequestAccount.php
  src/database/CheckUserIntegration.php
  src/database/DatabaseInteractions.php
  src/email.php
Labels: bug

#84 Call checkReadOnly when displaying special pages
  src/SpecialConfirmAccounts.php
  src/SpecialRequestAccount.php
Labels: bugfix

#86 re-edit for JS-disabled support
  resources/main.css
Labels: pr - needs work
